### PR TITLE
Port circular layout to JS

### PR DESCRIPTION
**Pull request by fedarko**
Includes a couple of fixes throughout other parts of the code, mainly to quiet jshint / prettier.

### CODE REVIEW

**Comment by fedarko** [comment]
OK, this should be ready for review / merging tomorrow. The circular layout here is actually more robust than the implementation in Python -- as a part of this, #184 is now addressed (so straight-line trees and/or trees with 1-child nodes are now guaranteed to be handled correctly, albeit a bit inefficiently due to #327).

Other noteworthy changes:

- removed scaling from the rectangular and circular layouts (per our discussion on slack; I think we can remove scaling from the unrooted layout also, but IDK how to do that without breaking it :)
- Added some (currently unused) parameters for the circular layout that we can later expose to the user through the UI when selecting a layout:
  - `startAngle`: the angle to assign the first tip to, in radians. Defaults to `0` (a.k.a. the first tip is placed at the rightmost side of the circle). Changing this just rotates the tree (so setting it to `Math.PI / 2` places the first tip at the top of the circle, etc.)
  - `ignoreLengths`: whether or not to ignore branch lengths during the layout. Defaults to `false` (a.k.a. don't ignore lengths, same as we've always done). Setting this to `true` replicates the sort of layout shown in #271 (although this does not close that issue; we still need to support this for the other 2 layouts and make a UI for this).

**Comment by kwcantrell** [comment]
Thanks @fedarko this looks good. I have removed scaling from the unrooted layout. A quick note, rotating the tree can be done much faster through WebGl by left multiplying the world matrix with a rotation matrix. Doing so will not require recomputing coordinates and is essentially free is terms of performance since it only involves a single matrix multiplication before passing the matrix to WebGl.

**Comment by fedarko** [comment]
Oh, that's awesome! Thanks for the heads up. Since circular layout is pretty quick I don't think having to recompute it to rotate the tree would be too bad, but if it gets to be a bottleneck it'd be nice to make it faster :) (Or if users decide they really want to, like, just have the tree rotating on the screen like a wheel then I guess we'd need to speed it up lol)

**Comment by kwcantrell** [comment]
I think we should add a global tree rotating property. Since we are just doing a single iteration of the unrooted layout, it would be nice to be able to rotate the tree manually so that the longer branches point toward the corners of the screen which would allow the user to fit more of the tree on screen when they zoom in.

**Comment by fedarko** [comment]
Completely didn't think about that -- yes, that would make a lot of sense, and doing it using a rotation matrix would generalize much more nicely to different layouts than implementing custom rotation code for each layout. Sounds good!

**Pull request merged**
